### ISSUE TITLE
Akka Http Tcp command [Connect(url:80,None,List(),Some(10 seconds),true)] failed because of akka.io.TcpOutgoingConnection$$anon$2: Connect timeout of Some(10 seconds)

### ISSUE THREAD

**Issue by ashishsahuGitHub** [akka/akka-meta#105]
Hi ,
I am facing below issue in Akka http  akka_actor='2.4.16', akka_http='10.1.8', akka_stream='2.5.22'.
[akka.actor.default-dispatcher-7] PoolGateway - Connection attempt failed. Backing off new connection attempts for at least 3200 milliseconds.

Tcp command [Connect,None,List(),Some(10 seconds),true)] failed because of akka.io.TcpOutgoingConnection$$anon$2: Connect timeout of Some(10 seconds)

And I have given the below settings
val orig = ConnectionPoolSettings(actorSystem.settings.config).copy(idleTimeout = 7 minutes)
  val clientSettings = orig.connectionSettings.withIdleTimeout(7 minutes)
  val settings = orig.copy(connectionSettings = clientSettings)
As well in application.conf
akka {
  jvm-exit-on-fatal-error = false
  akka.http.client.idle-timeout=60s
  akka.http.client.connecting-timeout=60s
  akka.http.host-connection-pool.idle-timeout=60s
  akka.http.host-connection-pool.client.idle-timeout=60s
  akka.http.host-connection-pool.pool-implementation = 60s
  http {
    host-connection-pool.client.idle-timeout = 60s
    client {
      idle-timeout = 60s
    }
  }
}

I am not getting the proper answer for this .
Pls let me know what else I can do in this ...

Regards,
Ashish Sahu

### Versions used 

Akka version: 

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

### Actual Behavior

Please provide a description of what actually happens, working from the same starting point.

### Relevant logs

If you identified a section in your logs that explains the bug or might be important to understand it, please add it.

### Reproducible Test Case

Please provide a PR with a failing test.

If the issue is more complex or requires configuration, please provide a link to a project that reproduces the issue.

**Comment by ashishsahuGitHub** [comment]
Hi,

More stack trace.....

ERROR[Actor-akka.actor.default-dispatcher-19] AkkaConsumerGeoJsonXYZProSpace$ - Stream errorakka.stream.StreamTcpException: Tcp command [Connect(url:80,None,List(),Some(10 seconds),true)] failed because of akka.io.TcpOutgoingConnection$$anon$2: Connect timeout of Some(10 seconds) expired
akka.stream.StreamTcpException: Tcp command [Connect(url:80,None,List(),Some(10 seconds),true)] failed because of akka.io.TcpOutgoingConnection$$anon$2: Connect timeout of Some(10 seconds) expired
Caused by: akka.io.TcpOutgoingConnection$$anon$2: Connect timeout of Some(10 seconds) expired
16:17:08.220UTC ERROR[Actor-akka.actor.default-dispatcher-5] Dispatcher - something wrong()
java.lang.RuntimeException: something wrong()
        at scala.sys.package$.error(package.scala:30)

**Comment by patriknw** [comment]
Hi, this is not the place to report issues, and we don’t use the issue tracker for questions.  Can you please ask it on https://discuss.akka.io ?

**Comment by ashishsahuGitHub** [comment]
Hi Patriknw,

Sure, I will do

**Comment by ashishsahuGitHub** [comment]
Hi,

But I can see so many geeks have reported the issue over here only.
Whats wrong with my issue ?
