### ISSUE TITLE
Code of Conduct: why was it changed and how can it improve?

### ISSUE THREAD

**Issue by rkuhn** [akka/akka-meta#120]
The Akka community is and has always been a pleasant and welcoming place, with thousands of individuals contributing to code and discussions over the past ten years (_a huge shout-out to everyone!_ ). With the introduction of the Gitter channels we summed this up in a brief statement:

> Instead of a long Code of Conduct we rely upon common sense: be kind and respectful to those who are already here and to those who come after you, harassment of any kind will not be tolerated; in case of trouble contact [akka.official](mailto:akka.official@gmail.com).

Two years ago, @ktoso adapted the Play framework Code of Conduct and added it to the main repository in akka/akka#23673, with the preamble that this is not a factual change — the addition was prompted by a general trend in the industry to spell out expectations even when that would not be necessitated by the concrete circumstances (as Konrad notes):

> This document does not change rules of engagement – please continue to be as nice and polite as you've always been in all online and real-life communication, thanks :-)

Now, a couple of weeks ago, @TimMoore has changed the situation without public discussion in akka/akka#27600 as part of a replacement of all previous rule sets in all Lightbend repositories. I spoke with him and the reason given was that harmonization of the rules for the different communities was the driving force, with the Scala community serving as the template. While this is an understandable goal for Lightbend, I would like to discuss whether the Akka community is not better served by a Code of Conduct that matches its own past instead of that of the Scala community, and whether all these communities are not better served by a Code of Conduct that is welcoming and inclusive.

That last point requires elaboration, please read on.

## Observations from looking at of some Codes of Conduct

Recently, I have started looking into Idris, which on the front-page links to their [Community Standards](https://www.idris-lang.org/documentation/community-standards/). If you follow that link you’ll find yourself on a friendly-looking page (text not crowded, black on white) that highlights four desirable qualities expected of all community members, each accompanied by one paragraph of text explaining what is meant in detail. The explanations are clear but also empathetic, talking to the reader in a friendly tone while be precise and firm.

Looking at the Rust [Code of Conduct](https://www.rust-lang.org/policies/code-of-conduct) (credited as inspiration by Lightbend), I find the font and color scheme to be not ideally suited from a pure psychology viewpoint — albeit matching the rest of the site. Apart from that, the Code is split into two parts, clearly distinguished by background color, and roughly equal in length. The first part talks about what community members are expected to do (again friendly “Please be kind and curteous” but also firm “We will exclude you from interaction if you insult, demean or harass anyone.”). The second part elaborates on the moderation processes and repeats several of the points from the first part.

Now turning our attention to the [Lightbend Code of Conduct](https://www.lightbend.com/conduct) we find ourselves on a page with warm colors and clear but not lofty font that uses the first of the Rust CoC points as a preamble, then credits the Scala CoC as the source of the rule set and dives into the standards, dividing those into _encouraged_ and _discouraged_ subsets. The encouraged set consists of four brief bullet points using imperative wording and showing little empathy for the reader — my perception upon first reading was that the tone borders on curt. Picturing some stranger talking to me like that, I would certainly not develop friendly feelings for that person. While there are four bullets of encouraged behavior, there are seventeen of discouraged behavior, the list does not fit on my computer screen. My impression when reading this as a newcomer will be “ouch, I need to be afraid of all these things happening in this community?”  —  because adding them here signals the need to clarify each of these points from past experience. The CoC then closes with a section on moderation that is similar to the Rust one, but with the repetitions removed.

## Discussion

In the previous section I put myself into the shoes of someone coming to a community for the first time and using the Code of Conduct as one important source of information on that community. Read like this, the currently linked Lightbend CoC does not match the Akka community, in fact the impression it conveys may rather turn someone away that welcome them. It is noteworthy that the structure of the text puts more focus on the bad stuff (i.e. the _excluded_ behaviors) than the good stuff (the _included_ behaviors). This is what I was referring to above: the Lightbend Code of Conduct putting more textual weight on exclusion makes it partly exclusive, regardless of the intent or the preamble.

Another point concerns exactly that preamble. Compare

> We are committed to providing a friendly, safe and welcoming environment for all, regardless of age, body size, disability, ethnicity, sex characteristics, gender identity and expression, level of experience, education, socio-economic status, nationality, personal appearance, race, religion, or sexual identity and orientation.

to

> The Idris community is committed to maintaining a welcoming, civil and constructive environment. We expect the following standards to be observed and upheld by all participants in any community forum (mailing lists, GitHub, IRC, reddit, etc.).

The former one lifts some part of the concrete rule set into the preamble while the latter gives a warm and friendly introduction and summary — the concrete list of rules against discrimination are then given in the first bullet point.

## My proposal

The intent behind the Code of Conduct is a good one, we need to make it obvious what our community standards are — friendly to well-meaning new members and if need be also painfully for malicious members. The best of both worlds can be achieved by starting out with a welcoming and truly inclusive description of desirable behaviors (inspired by the Idris example), with the delineation of discouraged behaviors woven in (like in the Rust example), followed by the moderation, domain, contact, and credits sections (like in the Lightbend example).

I invite every Akka contributor to give feedback on this proposal and have an open discussion so that we may come up with what is best for our community — I volunteer to draft a concrete text proposal in a PR once the discussion on this issue converges. And I hope to inspire other communities to follow our example.

**Comment by jlprat** [comment]
I'll start sharing a thought I had after reading the Lightbend CoC.
In my eyes there is too much weight on the excluded behaviors and I have a negative feeling after reading it. I guess this would completely change if those negative aspects were formulated using their reverse and then obviously go to the "encouraged behaviors".

So instead of:
> Avoid aggressive and micro-aggressive behavior, such as unconstructive criticism, providing corrections that do not improve the conversation (sometimes referred to as “well actually”s), repeatedly interrupting or talking over someone else, feigning surprise at someone’s lack of knowledge or awareness about a topic, or subtle prejudice (for example, comments like “That’s so easy my grandmother could do it.”). For more examples of this kind of behavior, see the Recurse Center’s user manual.

Something on the lines of:
> We encourage friendly communication and constructive feedback in all interactions within the community members...

**Comment by otto-dev** [comment]
> in fact the impression it conveys may rather turn someone away that welcome them. 

I'm a lay-community member and that's exactly the effect it had on me.

Any individual statement in the text, taken by itself may be fine, but it's the overall atmosphere and culture which is being communicated that can be repelling.

For me personally, I very much got this condescending self-righteous "inclusive progressive" kind of vibe. Sterile, self-assertive, self-righteous and condescending. Yuck. As was pointed out, the first thing is a lecture of 20-or-so bullet point points that I'm not to discriminate against. Is this a reflection of the tensions that are present in the community? Is this the atmosphere, and how you deal with each other? I wasn't going to discriminate anyone in the first place, but if that's the culture, I'd rather have nothing to do with you. - I'm just trying to communicate the feeling.

You can just tell me on a normal human level that you expect reasonable behavior.

**Comment by TimMoore** [comment]
@rkuhn is correct that one of our primary goals was unification on a common document for all of the projects maintained by Lightbend. This is one small way to give these projects more of a sense of unity, and helps people who are interacting with multiple projects by avoiding a proliferation of different codes that are similar, but not identical. The Scala Code of Conduct was chosen as the source for multiple reasons, including that it is an established document that has already been through multiple rounds of revision, is already used by Lightbend-maintained projects in the Scala GitHub organization, and has been adopted by other projects in the Scala community orbit, including [Typelevel](https://typelevel.org/code-of-conduct.html) and [ZIO](https://zio.dev/docs/about/about_coc).

It was also chosen because there is an established process for suggesting changes to it, and in fact the Scala Code of Conduct has iteratively evolved over time. I agree that all of these communities will be served best by a code of conduct that is welcoming and inclusive. My preference would be to improve the original Scala Code of Conduct document, and then keep the Lightbend Community Code of Conduct aligned with those changes. If that process isn't working, then we can reevaluate, but I'd like to at least try first.

The Scala Code of Conduct is maintained as a Markdown document at https://github.com/scala/scala-lang/blob/master/conduct.md and changes can be suggested by pull request. https://github.com/scala/scala-lang/pull/1079 is an example of a pull request I opened to reconcile it with suggestions made by various people within Lightbend that were incorporated in the version at https://www.lightbend.com/conduct. As I mentioned in the comments there, I wish in retrospect that we had made the changes in the source document first, and let them flow downstream. In the future, that's the process I'd like to follow.

**Comment by patriknw** [comment]
I support the idea of unification.

I agree that it would be good to make it more welcoming, and as a step towards that I have created PR https://github.com/scala/scala-lang/pull/1087 to move out the "Citizen Code of Conduct" examples from the main Discouraged section.

**Comment by rkuhn** [comment]
Following @patriknw’s lead I made the second part of the improvement proposal in scala/scala-lang#1089, let’s await the outcome of those discussions before proceeding here.

**Comment by TimMoore** [comment]
https://www.lightbend.com/conduct is now synced up with the upstream changes from  scala/scala-lang#1087 and scala/scala-lang#1089. Thanks for the collaboration on this.

**Comment by rkuhn** [comment]
Re-reading the new version from a distance I can with good conscience close this issue, thanks for the collaboration!

**Comment by patriknw** [comment]
Thanks for engaging and making things better, Roland.
