### ISSUE TITLE
Upcoming releases

### ISSUE THREAD

**Issue by ennru** [akka/akka-meta#133]
This issue lists releases we intend to get out during the next month or so. No guarantees these will happen in this order or time frame, though.

- [x] Akka 2.6.5 https://akka.io/blog/news/2020/04/30/akka-2.6.5-released
- [x] Lagom 1.6.2 https://github.com/lagom/lagom/releases/tag/1.6.2
- [x] Akka Persistence Cassandra 1.0.0-RC2 https://github.com/akka/akka-persistence-cassandra/releases/tag/v1.0.0-RC2
- [x] Akka Persistence JDBC 4.0.0-RC1 https://github.com/akka/akka-persistence-jdbc/releases/tag/v4.0.0-RC2
- [x] Akka HTTP 10.2.0-M1 https://doc.akka.io//docs/akka-http/10.2/release-notes/10.2.x.html
- [x] Alpakka 2.0.0 https://github.com/akka/alpakka/issues/2276
- [x] Akka Persistence Cassandra 1.0.0 https://github.com/akka/akka-persistence-cassandra/releases/tag/v1.0.0
	- Depends on Alpakka 2.0.0
- [x] Alpakka Kafka 2.0.3
- [x] Akka gRPC 1.0.0-M1 (https://github.com/akka/akka-grpc/issues/969)
- [x] Akka gRPC 1.0.0

**Comment by ennru** [comment]
- [x] Akka HTTP 10.2.0-M2

**Comment by ennru** [comment]
- [x] Play 2.8.2 https://github.com/playframework/play-meta/issues/156
- [x] Play 2.7.5 https://github.com/playframework/play-meta/issues/155

**Comment by patriknw** [comment]
- [x] Akka Persistence JDBC 4.0.0 final

**Comment by ennru** [comment]
- [x] Akka 2.6.6
- [x] Akka Management 1.0.8
- [x] Akka Persistence Cassandra 1.0.1
- [x] Alpakka 2.0.1

**Comment by ennru** [comment]
- [x] Akka gRPC 1.0.0 https://github.com/akka/akka-grpc/issues/1008

**Comment by ennru** [comment]
- [x] Akka HTTP 10.2.0 final

**Comment by patriknw** [comment]
- [x] Akka 2.6.7 (remember entities)

**Comment by ennru** [comment]
- [x] Alpakka Kafka 2.0.4

**Comment by ennru** [comment]
- [x] Akka gRPC 1.0.1 (improved Gradle support)

**Comment by ennru** [comment]
- [x] Lagom 1.6.3 (Akka 2.6.5 see [JacksonCborSerializer was using plain JSON format instead of CBOR.](https://doc.akka.io/docs/akka/current/project/rolling-update.html#2-6-5-jacksoncborserializer))
- [x] Lagom 1.6.4 (Akka 2.6.8 to finish the serialisation problem)

**Comment by patriknw** [comment]
* [x] Slick 3.3.3 (@renatocaval)

**Comment by ennru** [comment]
- [x] Alpakka Kafka 2.0.5 (version detection for Telemetry) https://github.com/akka/alpakka-kafka/issues/1191

**Comment by ennru** [comment]
- [x] Akka Projection 1.0.0 final

**Comment by patriknw** [comment]
- [x] Akka 2.6.9

**Comment by ennru** [comment]
- [x] Alpakka 2.0.2 https://github.com/akka/alpakka/milestone/44?closed=1

**Comment by ennru** [comment]
- [x] Akka HTTP 10.2.1

**Comment by raboof** [comment]
* [ ] Akka gRPC 1.1.0 https://github.com/akka/akka-grpc/issues/1129

**Comment by patriknw** [comment]
- [x] Akka 2.6.10 (sharding rolling update and rebalance improvements)

**Comment by ennru** [comment]
- [x] Alpakka Kafka 2.1.0-M1
- [ ] Alpakka 3.0.0-M1

**Comment by ennru** [comment]
- [x] Play 2.8.3 (Security fixes)
- [x] Play 2.7.6 (Security fixes)

**Comment by patriknw** [comment]
- [ ] Akka Projections 1.0.1 (TestKit compatibility with Akka 2.6.10)

**Comment by ennru** [comment]
- [x] Akka Management 1.0.9 
	https://github.com/akka/akka-management/issues/786 
	https://github.com/akka/akka-management/milestone/35?closed=1

**Comment by ennru** [comment]
- [x] Akka HTTP 10.1.13 https://github.com/akka/akka-http/issues/3620

**Comment by ennru** [comment]
- Akka HTTP 10.2.2 https://doc.akka.io/docs/akka-http/current/release-notes/10.2.x.html#10-2-2

**Comment by ennru** [comment]
- [x] Alpakka Kafka 2.0.6 (a few backports eg to re-establish Testcontainers support)

**Comment by patriknw** [comment]
- [x] Akka 2.6.11
- [ ] Akka Persistence Cassandra 1.0.5
- [x] Akka Persistence JDBC 5.0.0
- [x] Akka Projections 1.1.0

**Comment by patriknw** [comment]
- [x] Akka 2.6.12

**Comment by seglo** [comment]
- [ ] Alpakka Kafka 2.0.7
- [ ] Alpakka Kafka 2.1.0-RC1

**Comment by ennru** [comment]
As we are a smaller team nowadays, we don't need this coordination ticket anymore.
