### ISSUE TITLE
Migrate CI builds to GitHub Actions

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-meta#150]
Projects relying on docker to run a step of their CI build should move to GH Actions as soon as possible because of dockerhub rate-limiting policy affecting Travis.

- [x] https://github.com/akka/akka-management (in progress https://github.com/akka/akka-management/pull/889)
- [x] https://github.com/akka/akka-persistence-jdbc
- [ ] https://github.com/akka/akka-persistence-cassandra
- [ ] https://github.com/akka/akka-persistence-spanner
- [ ] https://github.com/akka/akka-persistence-couchbase
- [ ] https://github.com/akka/alpakka
- [x] https://github.com/akka/alpakka-kafka 
- [x] https://github.com/akka/akka-projection

Like in #149, it is OK if we only migrate the jobs of the complete CI build that need `docker`. It is not the goal of this issue to do a full migration from Travis to GitHub actions. The goal is to make builds less flaky.

**Comment by ennru** [comment]
We're good here.
