### ISSUE TITLE
Akka Sprint plan 2016-08-02 - Akka Streams Integrations

### ISSUE THREAD

**Issue by ktoso** [akka/akka-meta#24]
Start: 2016-08-02
End: 2016-08-19
Retrospective: 2016-08-19

## Strategy document

Codename "Project Alpakka"

Some parts of the team on vacations, be warned :)

## Artery

* [ ] Await community feedback

## Reactive Kafka

* [ ] Review and polish
* [ ] Prepare docs infrastructure for this project (preferably markdown-like based)
* [ ] Attempt to release a stable by the end of Sprint?
  * [ ] Coordinate with Reactive Kafka team

## Streams Integrations

We'll want to build examples of integrations.
The integrations will not be Lightbend supported, but we may publish them in any case (for example in akka-streams-contrib in some way).

* [ ] JMS
  * [ ] Investigate integrations; use as show case for integrating with legacy messaging systems
  * [ ] We want just a minimal thing to show how one would integrate
* [ ] FTP
  * [ ] possibly have a look at demand and possibilities for FTP originating streams
* [ ] Something to educate users about the connector system
* [ ] Maybe a twitter source
  * [ ] Both fun and "live" example
  * [ ] Would be a show case for JSON Streaming on client side.
* [ ] We have GraphStage documentation
  * [ ] Check if it's enough or not quite for people to grasp building integrations

* [ ] Other integration ideas (again, no promises about deliving, but we'll have a look at some of those)
    * [ ] Amqp ([http://www.amqp.org](http://www.amqp.org))
    * [ ] MQTT (Internet of things queues, provided by Amazon IoT, Azure IoT Hub, Heroku plugin: CloudMQTT). [PAHO Java library](https://eclipse.org/paho/clients/java/).
    * [ ] S3 ?
    * [ ] XML streaming (to complement what we have for JSON), real world still has tons of XML

## Akka Http

* [ ] Await community feedback
    * [ ] once confident release 2.4.9 stable
* [ ] Create akka-meta discussion on Akka HTTP versioning, and figure out how to best address compatibility vs. development once we declare stable

## Akka Streams

* [ ] The Hub!
    * Has to be fast
    * Worker pools example
    * Maybe chat example

## Akka Typed

* [ ] Reply in Roland’s threads
    * [https://github.com/akka/akka-meta/issues](https://github.com/akka/akka-meta/issues) 

## Bugs and failures

Bug start count: 26 
Failure start count: 37

Work on bugs and test failures are timeboxed to 4 days (Monday and Tuesday the first and second week). 

## Knowledge sharing

* [ ] Reviewed each other’s work, make sure team is evenly up to date on the various efforts while we spread out on the integrations

## Blog

* [ ] Write Akka HTTP Streaming blog post
    * Show how to build a custom one
    * encourage community to build them
* [ ] Write more blog posts about integration
    * No need to publish them yet, but each integration should have a post with it

## Releases

* 2.4.9 once confirmed to be stable
* Akka streams contrib during this sprint

**Comment by rkuhn** [comment]
Wow, that’s one looong sprint! :-)

**Comment by patriknw** [comment]
thanks for noticing, corrected

**Comment by ktoso** [comment]
Whoops, sorry for the typo :)

**Comment by patriknw** [comment]
# Outcome

> ## Artery
> 
> * [ ] Await community feedback

No specific feedback

> ## Reactive Kafka

> * [ ] Review and polish

done

> * [ ] Prepare docs infrastructure for this project (preferably markdown-like based)

done, Paradox: http://doc.akka.io/docs/akka-stream-kafka/current/home.html

> * [ ] Attempt to release a stable by the end of Sprint?
>   * [ ] Coordinate with Reactive Kafka team

RC1 done, good collaboration

> ## Streams Integrations
> 
> We'll want to build examples of integrations.
> The integrations will not be Lightbend supported, but we may publish them in any case (for example in akka-streams-contrib in some way).

done, prepared blog posts and code examples

* GraphStage getting started
* file "tail -f"
* directory watch
* AMQP
* MQTT
* Streaming XML parser

> ## Akka Http
> 
> * [ ] Await community feedback
>     * [ ] once confident release 2.4.9 stable

done

> * [ ] Create akka-meta discussion on Akka HTTP versioning, and figure out how to best address compatibility vs. development once we declare stable

done: https://github.com/akka/akka-meta/issues/27

> ## Akka Streams
> 
> * [ ] The Hub!

done, apart from documentation

> ## Akka Typed
> 
* [ ] Reply in Roland’s threads
    * [https://github.com/akka/akka-meta/issues](https://github.com/akka/akka-meta/issues) 

done

> ## Bugs and failures
> 
> Bug start count: 26 

end count: 28

> Failure start count: 37

end count: 36

> ## Knowledge sharing
> 
> * [ ] Reviewed each other’s work, make sure team is evenly up to date on the various efforts while we spread out on the integrations

done

> ## Blog
> 
> * [ ] Write Akka HTTP Streaming blog post

not done

> * [ ] Write more blog posts about integration
>     * No need to publish them yet, but each integration should have a post with it

done

> ## Releases
> 
> * 2.4.9 once confirmed to be stable

done

> * Akka streams contrib during this sprint

done
