### ISSUE TITLE
Zip | Unzip functionality with N items.

### ISSUE THREAD

**Issue by sirinath** [akka/akka-meta#4]
Zip and unzip taking just 2 items is a bit limiting. Perhaps you can support N items like ZipWith. More than Zip (as there is ZipWith) this is needed for UpZip

**Comment by ktoso** [comment]
Please open such tickets on http://github.com/akka/akka as they are about specific code things, not "general high level concepts" - which akka-meta is here for.

Concerning the UnzipWith - yes, there is a ticket for it already: https://github.com/akka/akka/issues/16965
