### ISSUE TITLE
Akka HTTP call for all

### ISSUE THREAD

**Issue by ktoso** [akka/akka-meta#43]
Hi hakkers,
we'd like to have another free-for-all Akka HTTP call.

Anyone who's interested in developing Akka HTTP is welcome to join.

Time: 
- **February, 22nd 17:00 CET**
- [Join the hangout](https://hangouts.google.com/hangouts/_/ytl/ZAlPkFUApC3J802gWMv4FpB0e2jkEKcyWWTsdI2NWds=?hl=en_US&authuser=1)
- [Watch](https://www.youtube.com/watch?v=raj7zhMM3w0)

Johannes knows everything there is to know about plans and codebase etc, so I don't think there's a need to delay it just because I'm away - we wanted to hold this call since January but travel made it too tricky.

Topics:
- Lightbend team update, what we'll focus on, and roadmap etc
  - We'll talk about HTTP/2 plans and timing, we'll work with Play team more closely together soon to get Akka HTTP as the engine in there - Konrad or Johannes 
- getting started / docs improvements, how to go about it - Josep
- declarative parsing / streaming - Jan
- simple high-level client infrastructure - gosubpl
- [your topic here, please propose below]

Let us know what time and topics would work for you!
The call will be on google hangouts and free to join for anyone who wants to.

**Comment by ktoso** [comment]
cc @jrudolph @akka/akka-http-team @jlprat @gosubpl

**Comment by jducoeur** [comment]
I'll probably mostly lurk, but am interested in listening in -- please keep me in the loop.  Either day currently looks clear for me.

**Comment by jlprat** [comment]
I think I can make it on the 22nd. On the 1st, unfortunately, I can't because of work.

**Comment by jlprat** [comment]
One topic I would like to bring in is about improving the "getting started" moment. Akka documentation in general has been always good once you know a bit about the project, but it generally lacks when somebody with no prior knowledge of it comes to the project. This was broad up in the akka-user group list (it was about akka, but I think it also can apply to akka-http), you can check the discussion [here](https://groups.google.com/forum/#!topic/akka-user/gOb03uyB0cE)
What about improving on this area? It could be done through tutorials, project templates, quick introduction guides.

**Comment by jypma** [comment]
Either would work for me. I plan on not getting ill this time :-) If I succeed, I can finally talk a bit about the declarative marshalling DSL and reactive XML+JSON parser stuff I was hoping to pull in from [ts-reaktive](https://github.com/Tradeshift/ts-reaktive/tree/master/ts-reaktive-marshal).

**Comment by jducoeur** [comment]
+1 to @jlprat's observation.  A few years ago, I was able to point folks to Activator templates to learn various aspects, but Activator seems to have lost steam, and I'm not sure we can rely on it any more...

**Comment by ktoso** [comment]
You'll be happy to hear the getting started experience is actually our top priority in the coming period (Lightbend-wise). Closely followed by HTTP/2 and other cool things :-)
So yeah, we'll definitely invest in a docs re-structuring / re-theming and general improvements - let's brainstorm in the call what we can do.

**Comment by gosubpl** [comment]
For me both dates would work fine but I prefer the 22nd.
In the 'getting started' vein I would like to discuss the possibility of adding a simple client like the one Spray has (has had :) ). This would simplify porting spray -> akka-http on projects that heavily use client in testing (e.g. mesosphere's marathon).
I would also like to talk about HTTP/2.

**Comment by ktoso** [comment]
Note: Let's do the call on the 22nd, next week then.

Simple client is a good discussion point - I feel we should help Play's WS (which has become a standalone thing) become awesome instead

**Comment by ShaneDelmore** [comment]
From a getting started with Akka-Http from Spray perspective I think the docs around migrating authentication could be improved. I found most of the migration easy but the authentication more difficult as the names and types had changed so much with no reference in the new codebase to the old types. A simple table of spray to Akka mappings like "Spray ContextAuthenticator => AkkaHttp ... would save users time when upgrading, especially since so much is practically free if you know the old to new imports to replace.

**Comment by jrudolph** [comment]
Thanks, @ktoso for organizing. Looking forward to next week!

**Comment by jypma** [comment]
How do we join tonight's call?

**Comment by jrudolph** [comment]
Hangout: https://hangouts.google.com/hangouts/_/ytl/N6Nvo3ZA1SUhQkGN7EPM2JUdr9R78tedJxAv9gTh_V0=?hl=en_US&authuser=1
Youtube: https://www.youtube.com/watch?v=zJWtVkBrXso

See you later!

**Comment by jypma** [comment]
Youtube? Fancy!

**Comment by jrudolph** [comment]
In fact, it's the same tech as always ;) Always takes 15 minutes to find the youtube account to use and then another 15 minutes to find the interface in youtube to actually schedule a Hangouts On Air...

**Comment by jrudolph** [comment]
The previous link was broken for some reason, please use this one:

https://hangouts.google.com/hangouts/_/ytl/ZAlPkFUApC3J802gWMv4FpB0e2jkEKcyWWTsdI2NWds=?hl=en_US&authuser=1

**Comment by jrudolph** [comment]
https://www.youtube.com/watch?v=raj7zhMM3w0

**Comment by jypma** [comment]
Slides I showed: http://htmlpreview.github.io/?https://github.com/Tradeshift/ts-reaktive/blob/master/ts-reaktive-marshal/doc/presentation.html (slide 14)

**Comment by jrudolph** [comment]
Closing this one, thanks again everyone for taking part!

**Comment by ktoso** [comment]
Thanks everyone! Still need to catch up on the entire video :-)
Welcome to the team @jlprat !

**Comment by jlprat** [comment]
Thanks!!
