### ISSUE TITLE
presentation of Java/Scala DSLs for Akka Typed

### ISSUE THREAD

**Issue by rkuhn** [akka/akka-meta#44]
The goal is to present a state of the API in 2.5.0 that can reasonably be declared final without modifications a few months later.

## Requirements

For both languages I’d like to achieve the following:

* it is possible to get access to the full DSL using a single import statement
* it is possible to import either the set of combinators directly, or their enclosing scope for disambiguation
* the name that is imported must be meaningful

## Proposal

**For Java:** create an interface `akka.typed.javadsl.Actor` that contains static methods for constructing Behaviors, e.g. using `Actor.<MyMsg>stateful((ctx, msg) -> ...)`.

**For Scala:** create an object `akka.typed.scaladsl.Actor` that contains the behavior constructors, e.g. `Actor.stateful[MyMsg]((ctx, msg) => ...)`.

The synchronization of these two DSLs would work out nicely because the only required language construct—lambda expressions—works nearly identically in both languages. This does entail a sweeping, breaking change of the current ScalaDSL, though. We could leave that object as is and deprecate it, to be removed when the new DSLs are declared final.

@akka/akka-committers please comment.

**Comment by johanandren** [comment]
I think it sounds good. Especially liked the `static import akka.typed.javadsl.Actor.*` part you mentioned on gitter, very neat.

I don't think we need to go through a deprecation mini-cycle with the current ScalaDSL, it is marked as experimental/may-change with extra research-topic warning signs in the docs etc.

**Comment by patriknw** [comment]
Sounds good, I agree with Johan regarding deprecation for 2.5.0. Just mention it in the migration guide.

**Comment by rkuhn** [comment]
While not strictly needed, I’d find it nicer to give people a chance for a migration that is not a big bang—considering that it does not cost us anything AFAICS. We can drop the old one in 2.5.1 for example.

**Comment by patriknw** [comment]
ok, no strong opinion

**Comment by jypma** [comment]
Would the Java variant properly infer types if written like
```
import static akka.typed.javadsl.Actor.stateful;
stateful((ctx, MyMsg msg) -> ...)
```
? That variant would at least also need an explicit type for `ctx`, which may be a disadvantage.

The reason I ask is, that the `MyClass.<SomeType>method()` syntax is a bit ugly and not that widely known.

**Comment by rkuhn** [comment]
@jypma Java does not really have much type inference to speak of, and in this case it is not reasonable to expect it either—even Scala cannot do this (Haskell probably could, but that is an entirely different universe). That “ugly” syntax is the only syntax provided by Java to explicitly supply the type argument to a method, so I don’t really see how we should get around it. It must also be widely known because it is required wherever a method takes a type parameter (yes, Java ≥8 can sometimes do without it, but only sometimes).

**Comment by rkuhn** [comment]
Good news, @jypma: one type ascription is enough, and it can be on the other side of the equals sign.
~~~java
  Behavior<MyMsg> actor1 = signalOrMessage((ctx, signal) -> same(),  (ctx, msg) -> stopped());
  Behavior<MyMsg> actor2 = stateful((ctx, msg) -> same());
  Behavior<MyMsg> actor3 = stateless((ctx, msg) -> unhandled());
  Behavior<MyMsg> actor4 = empty();
  Behavior<MyMsg> actor5 = ignore();
  Behavior<MyMsg> actor6 = tap((ctx, signal) -> {}, (ctx, msg) -> {}, actor5);
  Behavior<MyMsgA> actor7 = actor6.narrow();
  Behavior<MyMsg> actor8 = deferred(ctx -> {
    final ActorRef<MyMsg> self = ctx.self();
    return monitor(self, ignore());
  });
  Behavior<MyMsg> actor9 = widened(actor7, pf -> pf.match(MyMsgA.class, x -> x));
~~~
I think I’ll declare success!

**Comment by jypma** [comment]
Oh that's looking very neat indeed! Congratulations!

**Comment by patriknw** [comment]
Looks like this is done
