### ISSUE TITLE
Alpakka Sprint Plan 2018-06-25

### ISSUE THREAD

**Issue by 2m** [akka/akka-meta#74]
## Sprint plan Alpakka tea
This is going to be a two weeks sprint because of the upcoming vacations.

2 weeks
Start: 2018-06-25
End: 2018-07-06

### Team Members
* @2m
* @ennru

### Kafka Connector
* general focus on improving stability
* address failed tests tickets
* continue adding docker integration tests
* increase robustness when misconfigured/networking issues

### Alpakka
* general module for passthrough and no-message/message/multi-message 
* complete reference connector

### Other
* migrate to the latest paradox
* preparation for the webinar

### Issues and Pull Requests

This is going to be the fourth sprint.

|                          | Alpakka project | Reactive Kafka
|--------------------------|-----------------|---------------
|Issues start count        |             130 |             40
|Issues end count          |                 |             
|Closed issues start count |             339 |            195
|Closed issues end count   |                 |            
|PR start count            |              20 |              7
|PR end count              |                 |               
|Closed PRs start count    |             553 |            279
|Closed PRs end count      |                 |

**Comment by ennru** [comment]
### Kafka Connector
> * general focus on improving stability
> * address failed tests tickets
> * continue adding docker integration tests
> * increase robustness when misconfigured/networking issues

The Alpakka Kafka connector has now its own testkit supporting integration tests with Embedded Kafka and Kafka in Docker containers. It is the base for the benchmark tests, as well. The benchmark tests are now able to run on Travis.
The Scala code shown in the documentation is now run in unit tests, this discovered two minor issues of which one is fixed now.

### Alpakka
> * general module for passthrough and no-message/message/multi-message 

A PR from the community is being reviewed.

> * complete reference connector

The reference connector is now published with the Alpakka release 0.20.

### Other
> * migrate to the latest paradox

Done

> * preparation for the webinar

More to be done...

### Issues and Pull Requests

|                          | Alpakka project | Reactive Kafka
|--------------------------|-----------------|---------------
|Issues start count        |             130 |             40
|Issues end count          |             161 |             42
|Closed issues start count |             339 |            195
|Closed issues end count   |             347 |            196
|PR start count            |              20 |              7
|PR end count              |              16 |              9  
|Closed PRs start count    |             553 |            279
|Closed PRs end count      |             573 |            290
