### ISSUE TITLE
Akka sprint plan 2018-09-24

### ISSUE THREAD

**Issue by patriknw** [akka/akka-meta#84]
# Sprint plan for the core Akka team

4 weeks (extended to line up with Reactive Summit)
Start: 2018-09-24
End: 2018-10-19

## Lightbend orchestration

- Async DNS over TCP https://github.com/akka/akka/issues/25460
- Testing with Docker/Minikube on Travis https://github.com/akka/akka-management/issues/326
- Hardening of bootstrap and discovery (reported issues)
- More documentation improvements of Akka management/bootstrap https://github.com/akka/akka-management/pull/334
- Java and maven samples https://github.com/akka/akka-sample-cluster-kubernetes-java/pull/1

Stretch goal:
- explore approach for rolling updates
- Envoy cluster formation

## Akka Typed

- discussions, examples and decisions about persistence APIs
- other [tasks](https://github.com/akka/akka/projects/4)

## Other

* Look into Cassandra plugin [eventsByTag issue](https://github.com/akka/akka-persistence-cassandra/issues/383) 
* New attempt to build Akka and Akka HTTP for Scala 2.13-M5
* Complete Akka HTTP pool reconnect loop https://github.com/akka/akka-http/issues/1391
* Akka HTTP [fileUpload early response issue](https://github.com/akka/akka-http/issues/1216)
* Akka HTTP [aroundRequest](https://github.com/akka/akka-http/issues/2216)

## Bugs and failures

[Bug](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count:  11 / 625 (open / closed)
[Failure](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 45 / 534

Akka HTTP [Bug](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count: 46 / 121
Akka HTTP [Failure](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 29 / 69

**Comment by odd** [comment]
Does "Complete investigation of new Akka Persistence plugin" concern a specific persistence plugin (if so, which one?), or the persistence plugin architecture in general?

**Comment by patriknw** [comment]
It was for a specific database. Can’t share much details at the moment because it was a customer request and decisions are pending.

BTW, this thas has been completed in previous sprint. Copy pasta.

**Comment by odd** [comment]
Thanks! Always nice to have already completed items in the plan; provides a head start so to say 🤓

**Comment by patriknw** [comment]
# Outcome

> ## Lightbend orchestration

> - Async DNS over TCP https://github.com/akka/akka/issues/25460

Done, will be released in Akka 2.5.18 soon

> - Testing with Docker/Minikube on Travis https://github.com/akka/akka-management/issues/326

Done

> - Hardening of bootstrap and discovery (reported issues)

Done

> - More documentation improvements of Akka management/bootstrap https://github.com/akka/akka-management/pull/334

Done

> - Java and maven samples https://github.com/akka/akka-sample-cluster-kubernetes-java/pull/1

Done

> Stretch goal:
> - explore approach for rolling updates

Not done, but we have know how to do it and it should be documented

> - Envoy cluster formation

Not done

> ## Akka Typed
>
> - discussions, examples and decisions about persistence APIs

Done

> - other [tasks](https://github.com/akka/akka/projects/4)

Some progress

> ## Other

> * Look into Cassandra plugin [eventsByTag issue](https://github.com/akka/akka-persistence-cassandra/issues/383) 

Done

> * New attempt to build Akka and Akka HTTP for Scala 2.13-M5

Some progress, but considerable amount of work remaining. Next step will be to focus on a subset of Akka modules that would unlock Play.

> * Complete Akka HTTP pool reconnect loop https://github.com/akka/akka-http/issues/1391

Done

> * Akka HTTP [fileUpload early response issue](https://github.com/akka/akka-http/issues/1216)

Done

> * Akka HTTP [aroundRequest](https://github.com/akka/akka-http/issues/2216)

Not done

> ## Bugs and failures
>
> [Bug](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count:  11 / 625 (open / closed)

End count 12 / 629

> [Failure](https://github.com/akka/akka/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 45 / 534

53 / 536

> Akka HTTP [Bug](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Abug) start count: 46 / 121

43 / 127

> Akka HTTP [Failure](https://github.com/akka/akka-http/issues?q=is%3Aopen+is%3Aissue+label%3Afailed) start count: 29 / 69

23 / 76
